// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// InitialConfig is an autogenerated mock type for the InitialConfig type
type InitialConfig struct {
	mock.Mock
}

// GetAppStartupTime provides a mock function with given fields:
func (_m *InitialConfig) GetAppStartupTime() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// GetApplicationBinary provides a mock function with given fields:
func (_m *InitialConfig) GetApplicationBinary() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetApplicationSite provides a mock function with given fields:
func (_m *InitialConfig) GetApplicationSite() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHttpClient provides a mock function with given fields:
func (_m *InitialConfig) GetHttpClient() http.Client {
	ret := _m.Called()

	var r0 http.Client
	if rf, ok := ret.Get(0).(func() http.Client); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(http.Client)
	}

	return r0
}

// GetMongoConfigurationDatabase provides a mock function with given fields:
func (_m *InitialConfig) GetMongoConfigurationDatabase() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMongoConfigurationDbCollectionName provides a mock function with given fields:
func (_m *InitialConfig) GetMongoConfigurationDbCollectionName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMongoHostAndPort provides a mock function with given fields:
func (_m *InitialConfig) GetMongoHostAndPort() *string {
	ret := _m.Called()

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetSSLMode provides a mock function with given fields:
func (_m *InitialConfig) GetSSLMode() *string {
	ret := _m.Called()

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetSslCert provides a mock function with given fields:
func (_m *InitialConfig) GetSslCert() *string {
	ret := _m.Called()

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetSslKey provides a mock function with given fields:
func (_m *InitialConfig) GetSslKey() *string {
	ret := _m.Called()

	var r0 *string
	if rf, ok := ret.Get(0).(func() *string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}
