// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MongoAdapter is an autogenerated mock type for the MongoAdapter type
type MongoAdapter struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MongoAdapter) Close() {
	_m.Called()
}

// DeleteRecordUsingID provides a mock function with given fields: _a0, _a1
func (_m *MongoAdapter) DeleteRecordUsingID(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetClientConfigAll provides a mock function with given fields: _a0, _a1
func (_m *MongoAdapter) GetClientConfigAll(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetClientConfigBasedOnAppNameAndBinaryVersionAndSite provides a mock function with given fields: _a0, _a1
func (_m *MongoAdapter) GetClientConfigBasedOnAppNameAndBinaryVersionAndSite(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// InsertNewConfig provides a mock function with given fields: _a0, _a1
func (_m *MongoAdapter) InsertNewConfig(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
